### ISSUE TITLE
Edits for the README

### ISSUE THREAD

**Issue by MadisonJMyers** [IBM/sparksql-for-hbase#15]
Great work! Your README is clear and easy to follow. I did find a few small edits that I've suggested below:

- Add a comma after “developers familiar with SQL”
- Add periods to the end of all your bullet points so that you have consistency.
- Under 1. Install Apache Spark, Apache is misspelled in the third line. Please correct.
- Suggestion: maybe add how to add SPARK_HOME to the environment variable. Some users may not know how to do this. (Only a suggestion.)
- Under “Using Spark to access TPC-DS data” “Big Data systems” is capitalized. Is this a tool or proper noun? If not, please lowercase it.
- Under 1. Schemas please add a “the” before “TPC-DS definition.”
- Change the second sentence to: “Here is the schema (the primary keys in each table are underlined):”
- Under 4. Add a colon instead of a comma after “for example”

**Comment by rhagarty** [comment]
@MadisonJMyers thanks for the review. I will make the changes ASAP.

**Comment by MadisonJMyers** [comment]
Awesome! thanks @rhagarty

**Comment by bomeng** [comment]
Issue was resolved by Rich's PR.
